name: crud_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  csc_picker: ^0.2.7
  http: ^1.1.2
  gap: ^3.0.1
  provider: ^6.1.1
  mocktail: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
